"""add task ownership

Revision ID: 2ffb7c80999c
Revises: 1286e8739de0
Create Date: 2026-01-30 11:49:59.648660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffb7c80999c'
down_revision: Union[str, Sequence[str], None] = '1286e8739de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'owner_id')
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
